[package]
name = "term-typist"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.29.0"
ctrlc = "3.4.4"
dirs = "5.0.1"
rand = "0.8"
termion = "3.0.0"
tui = "0.19.0"
